Traceback (most recent call last):
  File "/home/josefine/miniconda3/envs/cb1020-dev/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/josefine/miniconda3/envs/cb1020-dev/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josefine/miniconda3/envs/cb1020-dev/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/josefine/miniconda3/envs/cb1020-dev/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/josefine/miniconda3/envs/cb1020-dev/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/josefine/miniconda3/envs/cb1020-dev/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/josefine/miniconda3/envs/cb1020-dev/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import torch
import torchvision
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mtorch[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mtorchvision[39;00m

File [0;32m~/miniconda3/envs/cb1020-dev/lib/python3.11/site-packages/torch/__init__.py:235[0m
[1;32m    233[0m     [38;5;28;01mif[39;00m USE_GLOBAL_DEPS:
[1;32m    234[0m         _load_global_deps()
[0;32m--> 235[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mtorch[39;00m[38;5;21;01m.[39;00m[38;5;21;01m_C[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m  [38;5;66;03m# noqa: F403[39;00m
[1;32m    237[0m [38;5;66;03m# Appease the type checker; ordinarily this binding is inserted by the[39;00m
[1;32m    238[0m [38;5;66;03m# torch._C module initialization code in C[39;00m
[1;32m    239[0m [38;5;28;01mif[39;00m TYPE_CHECKING:

[0;31mImportError[0m: libtorch_cpu.so: cannot enable executable stack as shared object requires: Invalid argument

