Traceback (most recent call last):
  File "/opt/miniconda3/envs/cb1020/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/miniconda3/envs/cb1020/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/envs/cb1020/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/miniconda3/envs/cb1020/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/miniconda3/envs/cb1020/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/miniconda3/envs/cb1020/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/envs/cb1020/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/miniconda3/envs/cb1020/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
i = 10     # integer
x = 3.1415 # float

a_list = [3.1, 'text', [1,2,3]] # list
b_dict = {'first': 'hello', 'second': x, 'third': a} # dictonary

print('Elements in list:')
for i, a in enumerate(a_list):
    print(i, a, a_list[i])

print('Elements in dictionary:')
for key in b_dict.keys():
    print('Key, value:', key, b_dict[key])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/xp/xqxvp53d2831kfb6dsx_zg5w0000gp/T/ipykernel_33233/2481259854.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0ma_list[0m [0;34m=[0m [0;34m[[0m[0;36m3.1[0m[0;34m,[0m [0;34m'text'[0m[0;34m,[0m [0;34m[[0m[0;36m1[0m[0;34m,[0m[0;36m2[0m[0;34m,[0m[0;36m3[0m[0;34m][0m[0;34m][0m [0;31m# list[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mb_dict[0m [0;34m=[0m [0;34m{[0m[0;34m'first'[0m[0;34m:[0m [0;34m'hello'[0m[0;34m,[0m [0;34m'second'[0m[0;34m:[0m [0mx[0m[0;34m,[0m [0;34m'third'[0m[0;34m:[0m [0ma[0m[0;34m}[0m [0;31m# dictonary[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0;34m[0m[0m
[1;32m      7[0m [0mprint[0m[0;34m([0m[0;34m'Elements in list:'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'a' is not defined
NameError: name 'a' is not defined

